PFORK(1)

# NAME

pfork - daemonize given program

# SYNOPSIS

*pfork* [--] program [ args... ]

# DESCRIPTION

The pfork utility executes and detaches the given program from terminal. Just
like a daemon.

# ENVIRONMENT

No environment yet.

# SEE ALSO

_setsid_(1)

# AUTHORS
- Originaly created by Ali Rıza Keskin <https://gitlab.com/sulincix>
- This version is released by kurth4cker <kurth4cker@gmail.com>
